### ISSUE TITLE
The raffle is not seen on mobile phones.

### ISSUE THREAD

**Issue by mcdeimon** [VidYen/VYPS#104]
Hi Felty,

The raffle is not seen on mobile phones.

**Comment by mcdeimon** [comment]
Yes, android and Chrome. I checked it and I can not see it on my phone. The Raffle and the "Current Game" panel.

Thanks!

**Comment by VidYen** [comment]
Thanks! Have to step out for a bit, but will have some waiting time to test it on my phone while in waiting line!
