### ISSUE TITLE
VYPS_cg having to enter everything again after forgetting to fill in one field

### ISSUE THREAD

**Issue by VidYen** [VidYen/VYPS#14]
Not terribly critical, but I noticed if you forget to fill out something like "entrenchment" or "speed", that the form resets and you have to fill out everything again.

Which admins will eventually remember to fill out everything, but I by default all the stats should be zero and if admin forgets to set them, he can go back in later.

For example... Some units will have no entrenchment or armor so it makes sense to have it default to zero to speed things up anyways and if site admin forgets they can go back in later.

**Comment by oclin** [comment]
Still working on it, it's not yet complete and I have a local version that is further ahead.

**Comment by VidYen** [comment]
Ah no problem. Its all coming together nicely!

Also wanted to say in some cases things can have 0 entrenchment like it were a flying unit.
